# Generated by Django 5.0.6 on 2024-11-05 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='council',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tehsil',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.division'),
            preserve_default=False,
        ),
    ]
