# Generated by Django 5.0.6 on 2024-11-05 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_candidate_division_council_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='polling_booth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.pollingbooth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votertable',
            name='polling_booth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.pollingbooth'),
            preserve_default=False,
        ),
    ]
