# Generated by Django 5.0.6 on 2024-09-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_votertable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votertable',
            name='cnic',
            field=models.CharField(default=1, max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
