# Generated by Django 5.0.6 on 2024-11-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_candidate_polling_booth_votertable_polling_booth'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingbooth',
            name='gender',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
