# Generated by Django 5.0.6 on 2024-11-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pollingbooth_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='gender',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
