# Generated by Django 5.0.6 on 2024-10-31 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_candidate_modified_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='council',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='district',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='division',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='pollingstation',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='province',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='tehsil',
            name='date_joined',
        ),
    ]
