# Generated by Django 5.0.6 on 2024-11-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_vote_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
