# Generated by Django 5.0.6 on 2024-11-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_candidate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cnic',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='date_of_birth',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='father_name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
