# Generated by Django 5.0.6 on 2024-10-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_council_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollingstation',
            name='division',
        ),
        migrations.RemoveField(
            model_name='council',
            name='division',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
    ]
