# Generated by Django 5.0.6 on 2024-11-03 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='votertable',
            name='polling_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.pollingstation'),
            preserve_default=False,
        ),
    ]
