# Generated by Django 5.0.6 on 2024-11-04 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_votertable_polling_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votertable',
            name='division',
        ),
        migrations.AddField(
            model_name='votertable',
            name='council',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.council'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votertable',
            name='district',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votertable',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votertable',
            name='tehsil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.tehsil'),
            preserve_default=False,
        ),
    ]
