# Generated by Django 5.0.6 on 2024-11-07 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_vote_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='transaction_id',
        ),
        migrations.CreateModel(
            name='CatsedVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vote', unique=True)),
            ],
        ),
    ]
