# Generated by Django 5.0.6 on 2024-11-04 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_votertable_division_votertable_council_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='council',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.council'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='district',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='tehsil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.tehsil'),
            preserve_default=False,
        ),
    ]
