# Generated by Django 5.0.6 on 2024-11-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_vote_transaction_id_catsedvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catsedvote',
            name='vote',
        ),
    ]
