# Generated by Django 5.0.6 on 2024-11-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_catsedvote_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPart1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPart2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPart3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=255)),
            ],
        ),
    ]
